language: ruby
rvm:
  - 2.1.2
env:
  - DB=mysql
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database footyshares_test'
  - psql -c 'create database footyshares_test' -U postgres
