mysql: &mysql
  adapter: mysql2
  encoding: utf8
  reconnect: false
  username: root
  password:
  database: footyshares_<%= Rails.env %>

postgresql: &postgresql
  adapter: postgresql
  username: postgres
  password:
  database: footyshares_<%= Rails.env %>
  min_messages: ERROR

defaults: &defaults
  host: localhost
  pool: 5
  socket: /var/run/mysqld/mysqld.sock
  <<: *<%= ENV['DB'] || "postgresql" %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults